// Code generated by mfd-generator unknown; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	Category struct {
		ID, Title, OrderNumber, StatusID string
	}
	News struct {
		ID, Title, Preview, Content, CategoryID, CountryID, RegionID, CityID, TagIDs, CreatedAt, PublishedAt, StatusID string

		Category, Country, Region, City string
	}
	Tag struct {
		ID, Title, StatusID string
	}
	City struct {
		ID, RegionID, Title, AltTitle, Alias, OrderNumber, StatusID, CountryID string

		Region, Country string
	}
	Country struct {
		ID, Title, AltTitle, Alias, OrderNumber, H1, PageTitle, MetaDescription, StatusID string
	}
	Region struct {
		ID, CountryID, Title, AltTitle, Alias, OrderNumber, Image, H1, PageTitle, MetaDescription, StatusID string

		Country string
	}
}{
	Category: struct {
		ID, Title, OrderNumber, StatusID string
	}{
		ID:          "categoryId",
		Title:       "title",
		OrderNumber: "orderNumber",
		StatusID:    "statusId",
	},
	News: struct {
		ID, Title, Preview, Content, CategoryID, CountryID, RegionID, CityID, TagIDs, CreatedAt, PublishedAt, StatusID string

		Category, Country, Region, City string
	}{
		ID:          "newsId",
		Title:       "title",
		Preview:     "preview",
		Content:     "content",
		CategoryID:  "categoryId",
		CountryID:   "countryId",
		RegionID:    "regionId",
		CityID:      "cityId",
		TagIDs:      "tagIds",
		CreatedAt:   "createdAt",
		PublishedAt: "publishedAt",
		StatusID:    "statusId",

		Category: "Category",
		Country:  "Country",
		Region:   "Region",
		City:     "City",
	},
	Tag: struct {
		ID, Title, StatusID string
	}{
		ID:       "tagId",
		Title:    "title",
		StatusID: "statusId",
	},
	City: struct {
		ID, RegionID, Title, AltTitle, Alias, OrderNumber, StatusID, CountryID string

		Region, Country string
	}{
		ID:          "cityId",
		RegionID:    "regionId",
		Title:       "title",
		AltTitle:    "altTitle",
		Alias:       "alias",
		OrderNumber: "orderNumber",
		StatusID:    "statusId",
		CountryID:   "countryId",

		Region:  "Region",
		Country: "Country",
	},
	Country: struct {
		ID, Title, AltTitle, Alias, OrderNumber, H1, PageTitle, MetaDescription, StatusID string
	}{
		ID:              "countryId",
		Title:           "title",
		AltTitle:        "altTitle",
		Alias:           "alias",
		OrderNumber:     "orderNumber",
		H1:              "h1",
		PageTitle:       "pageTitle",
		MetaDescription: "metaDescription",
		StatusID:        "statusId",
	},
	Region: struct {
		ID, CountryID, Title, AltTitle, Alias, OrderNumber, Image, H1, PageTitle, MetaDescription, StatusID string

		Country string
	}{
		ID:              "regionId",
		CountryID:       "countryId",
		Title:           "title",
		AltTitle:        "altTitle",
		Alias:           "alias",
		OrderNumber:     "orderNumber",
		Image:           "image",
		H1:              "h1",
		PageTitle:       "pageTitle",
		MetaDescription: "metaDescription",
		StatusID:        "statusId",

		Country: "Country",
	},
}

var Tables = struct {
	Category struct {
		Name, Alias string
	}
	News struct {
		Name, Alias string
	}
	Tag struct {
		Name, Alias string
	}
	City struct {
		Name, Alias string
	}
	Country struct {
		Name, Alias string
	}
	Region struct {
		Name, Alias string
	}
}{
	Category: struct {
		Name, Alias string
	}{
		Name:  "categories",
		Alias: "t",
	},
	News: struct {
		Name, Alias string
	}{
		Name:  "news",
		Alias: "t",
	},
	Tag: struct {
		Name, Alias string
	}{
		Name:  "tags",
		Alias: "t",
	},
	City: struct {
		Name, Alias string
	}{
		Name:  "cities",
		Alias: "t",
	},
	Country: struct {
		Name, Alias string
	}{
		Name:  "countries",
		Alias: "t",
	},
	Region: struct {
		Name, Alias string
	}{
		Name:  "regions",
		Alias: "t",
	},
}

type Category struct {
	tableName struct{} `pg:"categories,alias:t,discard_unknown_columns"`

	ID          int    `pg:"categoryId,pk"`
	Title       string `pg:"title,use_zero"`
	OrderNumber int    `pg:"orderNumber,use_zero"`
	StatusID    int    `pg:"statusId,use_zero"`
}

type News struct {
	tableName struct{} `pg:"news,alias:t,discard_unknown_columns"`

	ID          int        `pg:"newsId,pk"`
	Title       string     `pg:"title,use_zero"`
	Preview     *string    `pg:"preview"`
	Content     *string    `pg:"content"`
	CategoryID  int        `pg:"categoryId,use_zero"`
	CountryID   *int       `pg:"countryId"`
	RegionID    *int       `pg:"regionId"`
	CityID      *int       `pg:"cityId"`
	TagIDs      []int      `pg:"tagIds,array"`
	CreatedAt   time.Time  `pg:"createdAt,use_zero"`
	PublishedAt *time.Time `pg:"publishedAt"`
	StatusID    int        `pg:"statusId,use_zero"`

	Category *Category `pg:"fk:categoryId,rel:has-one"`
	Country  *Country  `pg:"fk:countryId,rel:has-one"`
	Region   *Region   `pg:"fk:regionId,rel:has-one"`
	City     *City     `pg:"fk:cityId,rel:has-one"`
}

type Tag struct {
	tableName struct{} `pg:"tags,alias:t,discard_unknown_columns"`

	ID       int    `pg:"tagId,pk"`
	Title    string `pg:"title,use_zero"`
	StatusID int    `pg:"statusId,use_zero"`
}

type City struct {
	tableName struct{} `pg:"cities,alias:t,discard_unknown_columns"`

	ID          int     `pg:"cityId,pk"`
	RegionID    int     `pg:"regionId,use_zero"`
	Title       string  `pg:"title,use_zero"`
	AltTitle    *string `pg:"altTitle"`
	Alias       string  `pg:"alias,use_zero"`
	OrderNumber int     `pg:"orderNumber,use_zero"`
	StatusID    int     `pg:"statusId,use_zero"`
	CountryID   int     `pg:"countryId,use_zero"`

	Region  *Region  `pg:"fk:regionId,rel:has-one"`
	Country *Country `pg:"fk:countryId,rel:has-one"`
}

type Country struct {
	tableName struct{} `pg:"countries,alias:t,discard_unknown_columns"`

	ID              int     `pg:"countryId,pk"`
	Title           string  `pg:"title,use_zero"`
	AltTitle        *string `pg:"altTitle"`
	Alias           string  `pg:"alias,use_zero"`
	OrderNumber     int     `pg:"orderNumber,use_zero"`
	H1              *string `pg:"h1"`
	PageTitle       *string `pg:"pageTitle"`
	MetaDescription *string `pg:"metaDescription"`
	StatusID        int     `pg:"statusId,use_zero"`
}

type Region struct {
	tableName struct{} `pg:"regions,alias:t,discard_unknown_columns"`

	ID              int     `pg:"regionId,pk"`
	CountryID       int     `pg:"countryId,use_zero"`
	Title           string  `pg:"title,use_zero"`
	AltTitle        *string `pg:"altTitle"`
	Alias           string  `pg:"alias,use_zero"`
	OrderNumber     int     `pg:"orderNumber,use_zero"`
	Image           *string `pg:"image"`
	H1              *string `pg:"h1"`
	PageTitle       *string `pg:"pageTitle"`
	MetaDescription *string `pg:"metaDescription"`
	StatusID        int     `pg:"statusId,use_zero"`

	Country *Country `pg:"fk:countryId,rel:has-one"`
}
