-- =============================================================================
-- Diagram Name: test
-- Created on: 14.03.2023 12:05:11
-- Diagram Version: 
-- =============================================================================

CREATE TABLE "news" (
	"newsId" SERIAL NOT NULL,
	"title" varchar(255) NOT NULL,
	"preview" varchar(255),
	"content" text,
	"categoryId" int4 NOT NULL,
    "countryId" int4,
    "regionId" int4,
    "cityId" int4,
	"tagIds" int4[],
	"createdAt" timestamp with time zone NOT NULL DEFAULT NOW(),
	"publishedAt" timestamp with time zone,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("newsId")
);

COMMENT ON COLUMN "news"."newsId" IS 'id новости';

COMMENT ON COLUMN "news"."title" IS 'Заголовок новости';

COMMENT ON COLUMN "news"."preview" IS 'Ссылка на фото-превью новости';

COMMENT ON COLUMN "news"."content" IS 'Контент новости';

CREATE TABLE "statuses" (
	"statusId" SERIAL NOT NULL,
	PRIMARY KEY("statusId")
);

CREATE TABLE "categories" (
	"categoryId" SERIAL NOT NULL,
	"title" varchar(255) NOT NULL,
	"orderNumber" int4 NOT NULL,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("categoryId")
);

CREATE TABLE "tags" (
	"tagId" SERIAL NOT NULL,
	"title" varchar(255) NOT NULL,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("tagId")
);

CREATE TABLE "countries" (
                             "countryId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                             "title" varchar(255) NOT NULL,
                             "altTitle" varchar(255),
                             "alias" varchar(255) NOT NULL,
                             "orderNumber" int4 NOT NULL,
                             "h1" varchar(500),
                             "pageTitle" varchar(500),
                             "metaDescription" varchar(1000),
                             "statusId" int4 NOT NULL,
                             PRIMARY KEY("countryId")
);

CREATE TABLE "regions" (
                           "regionId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                           "countryId" int4 NOT NULL,
                           "title" varchar(255) NOT NULL,
                           "altTitle" varchar(255),
                           "alias" varchar(255) NOT NULL,
                           "orderNumber" int4 NOT NULL,
                           "image" varchar(32),
                           "h1" varchar(500),
                           "pageTitle" varchar(500),
                           "metaDescription" varchar(1000),
                           "statusId" int4 NOT NULL,
                           PRIMARY KEY("regionId")
);

CREATE TABLE "cities" (
                          "cityId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                          "regionId" int4 NOT NULL,
                          "countryId" int4 NOT NULL,
                          "title" varchar(255) NOT NULL,
                          "altTitle" varchar(255),
                          "alias" varchar(255) NOT NULL,
                          "orderNumber" int4 NOT NULL,
                          "statusId" int4 NOT NULL,
                          PRIMARY KEY("cityId")
);

COMMENT ON COLUMN "tags"."tagId" IS 'id тега';

COMMENT ON COLUMN "tags"."title" IS 'Текст тега';


ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_categories" FOREIGN KEY ("categoryId")
	REFERENCES "categories"("categoryId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_countries" FOREIGN KEY ("countryId")
    REFERENCES "countries"("countryId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_regions" FOREIGN KEY ("regionId")
    REFERENCES "regions"("regionId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_cities" FOREIGN KEY ("cityId")
    REFERENCES "cities"("cityId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "categories" ADD CONSTRAINT "Ref_categories_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "tags" ADD CONSTRAINT "Ref_tags_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "countries" ADD CONSTRAINT "Ref_countries_to_statuses" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "regions" ADD CONSTRAINT "Ref_regions_to_statuses" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "regions" ADD CONSTRAINT "Ref_regions_to_countries" FOREIGN KEY ("countryId")
    REFERENCES "countries"("countryId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "cities" ADD CONSTRAINT "Ref_cities_to_countries" FOREIGN KEY ("countryId")
    REFERENCES "countries"("countryId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "cities" ADD CONSTRAINT "Ref_cities_to_regions" FOREIGN KEY ("regionId")
    REFERENCES "regions"("regionId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "cities" ADD CONSTRAINT "Ref_cities_to_statuses" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
