-- =============================================================================
-- Diagram Name: test
-- Created on: 14.03.2023 12:05:11
-- Diagram Version: 
-- =============================================================================

CREATE TABLE "news" (
	"newsId" SERIAL NOT NULL,
	"title" varchar(255) NOT NULL,
	"preview" varchar(255),
	"content" text,
	"categoryId" int4 NOT NULL,
    "countryId" int4,
    "regionId" int4,
    "cityId" int4,
	"tagIds" int4[],
	"createdAt" timestamp with time zone NOT NULL DEFAULT NOW(),
	"publishedAt" timestamp with time zone,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("newsId")
);

COMMENT ON COLUMN "news"."newsId" IS 'id новости';

COMMENT ON COLUMN "news"."title" IS 'Заголовок новости';

COMMENT ON COLUMN "news"."preview" IS 'Ссылка на фото-превью новости';

COMMENT ON COLUMN "news"."content" IS 'Контент новости';

CREATE TABLE "statuses" (
	"statusId" SERIAL NOT NULL,
	PRIMARY KEY("statusId")
);

CREATE TABLE "categories" (
	"categoryId" SERIAL NOT NULL,
	"title" varchar(255) NOT NULL,
	"orderNumber" int4 NOT NULL,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("categoryId")
);

CREATE TABLE "tags" (
	"tagId" SERIAL NOT NULL,
	"title" varchar(255) NOT NULL,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("tagId")
);

CREATE TABLE "countries" (
                             "countryId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                             "title" varchar(255) NOT NULL,
                             "altTitle" varchar(255),
                             "alias" varchar(255) NOT NULL,
                             "orderNumber" int4 NOT NULL,
                             "h1" varchar(500),
                             "pageTitle" varchar(500),
                             "metaDescription" varchar(1000),
                             "statusId" int4 NOT NULL,
                             PRIMARY KEY("countryId")
);

CREATE TABLE "regions" (
                           "regionId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                           "countryId" int4 NOT NULL,
                           "title" varchar(255) NOT NULL,
                           "altTitle" varchar(255),
                           "alias" varchar(255) NOT NULL,
                           "orderNumber" int4 NOT NULL,
                           "image" varchar(32),
                           "h1" varchar(500),
                           "pageTitle" varchar(500),
                           "metaDescription" varchar(1000),
                           "statusId" int4 NOT NULL,
                           PRIMARY KEY("regionId")
);

CREATE TABLE "cities" (
                          "cityId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                          "regionId" int4 NOT NULL,
                          "countryId" int4 NOT NULL,
                          "title" varchar(255) NOT NULL,
                          "altTitle" varchar(255),
                          "alias" varchar(255) NOT NULL,
                          "orderNumber" int4 NOT NULL,
                          "statusId" int4 NOT NULL,
                          PRIMARY KEY("cityId")
);

COMMENT ON COLUMN "tags"."tagId" IS 'id тега';

COMMENT ON COLUMN "tags"."title" IS 'Текст тега';

CREATE TABLE "vfsFiles" (
                            "fileId" SERIAL NOT NULL,
                            "folderId" int4 NOT NULL,
                            "title" varchar(255) NOT NULL,
                            "path" varchar(255) NOT NULL,
                            "params" text,
                            "isFavorite" bool DEFAULT false,
                            "mimeType" varchar(255) NOT NULL,
                            "fileSize" int4 DEFAULT 0,
                            "fileExists" bool NOT NULL DEFAULT true,
                            "createdAt" timestamp NOT NULL DEFAULT now(),
                            "statusId" int4 NOT NULL,
                            CONSTRAINT "vfsFiles_pkey" PRIMARY KEY("fileId")
);

CREATE INDEX "IX_FK_vfsFiles_folderId_vfsFiles" ON "vfsFiles" USING BTREE (
    "folderId"
    );


CREATE INDEX "IX_FK_vfsFiles_statusId_vfsFiles" ON "vfsFiles" USING BTREE (
    "statusId"
    );


CREATE TABLE "vfsFolders" (
                              "folderId" SERIAL NOT NULL,
                              "parentFolderId" int4,
                              "title" varchar(255) NOT NULL,
                              "isFavorite" bool DEFAULT false,
                              "createdAt" timestamp NOT NULL DEFAULT now(),
                              "statusId" int4 NOT NULL,
                              CONSTRAINT "vfsFolders_pkey" PRIMARY KEY("folderId")
);

CREATE INDEX "IX_FK_vfsFolders_folderId_vfsFolders" ON "vfsFolders" USING BTREE (
    "parentFolderId"
    );


CREATE INDEX "IX_FK_vfsFolders_statusId_vfsFolders" ON "vfsFolders" USING BTREE (
    "statusId"
    );


CREATE TABLE "vfsHashes" (
                             "hash" varchar(40) NOT NULL,
                             "namespace" varchar(32) NOT NULL,
                             "extension" varchar(4) NOT NULL,
                             "fileSize" int4 NOT NULL DEFAULT 0,
                             "width" int4 NOT NULL DEFAULT 0,
                             "height" int4 NOT NULL DEFAULT 0,
                             "blurhash" text,
                             "error" text,
                             "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
                             "indexedAt" timestamp with time zone,
                             CONSTRAINT "vfsHashes_pkey" PRIMARY KEY("hash","namespace")
);

CREATE INDEX "IX_vfsHashes_indexedAt" ON "vfsHashes" USING BTREE (
    "indexedAt"
    );

ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_categories" FOREIGN KEY ("categoryId")
	REFERENCES "categories"("categoryId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_countries" FOREIGN KEY ("countryId")
    REFERENCES "countries"("countryId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_regions" FOREIGN KEY ("regionId")
    REFERENCES "regions"("regionId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_cities" FOREIGN KEY ("cityId")
    REFERENCES "cities"("cityId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "categories" ADD CONSTRAINT "Ref_categories_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "tags" ADD CONSTRAINT "Ref_tags_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "countries" ADD CONSTRAINT "Ref_countries_to_statuses" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "regions" ADD CONSTRAINT "Ref_regions_to_statuses" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "regions" ADD CONSTRAINT "Ref_regions_to_countries" FOREIGN KEY ("countryId")
    REFERENCES "countries"("countryId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "cities" ADD CONSTRAINT "Ref_cities_to_countries" FOREIGN KEY ("countryId")
    REFERENCES "countries"("countryId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "cities" ADD CONSTRAINT "Ref_cities_to_regions" FOREIGN KEY ("regionId")
    REFERENCES "regions"("regionId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "cities" ADD CONSTRAINT "Ref_cities_to_statuses" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

ALTER TABLE "vfsFiles" ADD CONSTRAINT "vfsFiles_folderId_fkey" FOREIGN KEY ("folderId")
    REFERENCES "vfsFolders"("folderId")
    MATCH SIMPLE
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;

ALTER TABLE "vfsFiles" ADD CONSTRAINT "vfsFiles_statusId_fkey" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    MATCH SIMPLE
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;

ALTER TABLE "vfsFolders" ADD CONSTRAINT "vfsFolders_parentFolderId_fkey" FOREIGN KEY ("parentFolderId")
    REFERENCES "vfsFolders"("folderId")
    MATCH SIMPLE
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;

ALTER TABLE "vfsFolders" ADD CONSTRAINT "vfsFolders_statusId_fkey" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    MATCH SIMPLE
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;

CREATE TABLE "encryptionKeys" (
    "encryptionKeyId" uuid NOT NULL DEFAULT gen_random_uuid(),
    "issuedCount" int4 NOT NULL DEFAULT 0,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone,
    "expiresAt" timestamp with time zone NOT NULL,
    "statusId" int4 NOT NULL,
    PRIMARY KEY("encryptionKeyId")
);

CREATE INDEX "encryptionKeys_issuedCount_index" ON "encryptionKeys" ("issuedCount");

CREATE INDEX "encryptionKeys_statusId_index" ON "encryptionKeys" ("statusId");

ALTER TABLE "encryptionKeys" ADD CONSTRAINT "Ref_encryptionKeys_to_statuses" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    MATCH SIMPLE
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;

CREATE TABLE "siteUsers" (
    "siteUserId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "statusId" int4 NOT NULL,
    "email" varchar(255) NOT NULL,
    "defaultRole" varchar(32) NOT NULL,
    "password" varchar(255),
    "firstName" varchar(255),
    "lastName" varchar(255),
    "ownerExternalId" int8,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "lastActivityAt" timestamp with time zone,
    PRIMARY KEY("siteUserId")
);

ALTER TABLE "siteUsers" ADD CONSTRAINT "FK_siteUsers_statusId" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    MATCH SIMPLE
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

CREATE TABLE "loginCodes" (
    "state" text NOT NULL,
    "code" varchar(8) NOT NULL,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "siteUserId" int4 NOT NULL,
    "attempts" int4 NOT NULL DEFAULT 0,
    PRIMARY KEY("state")
);

ALTER TABLE "loginCodes" ADD CONSTRAINT "FK_loginCodes_siteUserId" FOREIGN KEY ("siteUserId")
    REFERENCES "siteUsers"("siteUserId")
    MATCH SIMPLE
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;
